language: android

jdk:
  - oraclejdk8

before_install:
    - chmod +x gradlew

script:
     - ./gradlew assembleDebug
    
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - platform-tools
    # - tools

    # The BuildTools version used by your project
    - tools
    - build-tools-23.0.2

    # The SDK version used to compile your project
    - android-24

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19
